### ISSUE TITLE
FHRS URL update

### ISSUE THREAD

**Issue by UKChris-osm** [gregrs-uk/fhodot#16]
I've just noticed on the FSA Web site that they are [changing their API URL](https://www.food.gov.uk/news-alerts/news/fhrs-api-v1-update), so thought I would post that here just in case it impacts on the project.

**Comment by kmpoppe** [comment]
Thanks for digging that out @UKChris-osm, will have to change that in my project as well :-)

**Comment by gregrs-uk** [comment]
Thanks for flagging this, @UKChris-osm. [This project uses the v2 API](https://github.com/gregrs-uk/fhodot/blob/4a1ba8f55e48abc14715084af94440259546a710/fhodot/fetch_fhrs.py#L71) so I believe that no change is needed.
