### ISSUE TITLE
Fix local authority districts on development server

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/fhodot#18]
Data updates are currently failing with `RuntimeError: Database has 376 authorities but new data only has 363`.

Presumably related to [this](https://en.wikipedia.org/wiki/2019%E2%80%932023_structural_changes_to_local_government_in_England#Changes_in_2023).

**Comment by gregrs-uk** [comment]
Updated boundaries not yet available from [ONS](https://geoportal.statistics.gov.uk), although updated [names and codes](https://geoportal.statistics.gov.uk/maps/local-authority-districts-april-2023-names-and-codes-in-the-united-kingdom) have been released. Have emailed ONS.

**Comment by jnicho02** [comment]
The new Local Authorities are going to be amalgamations so ONS will
probably be there fairly soon...or you could make your own.

**Comment by gregrs-uk** [comment]
The new boundaries appear to be available on the ONS site now, but I won't have time to fix this for a little while. If anyone wants to tackle it, the statistics will need mapping so that old stats for regions that have been merged are combined, as is already the case for some previous boundary changes.

**Comment by KasperFranz** [comment]
@gregrs-uk  I have now fixed this in the pull request #21  is it something you can review?

**Comment by gregrs-uk** [comment]
Thanks @KasperFranz – much appreciated. I had already started working on this a while ago without pushing my changes. I'll try to compare our versions over the next few days.

**Comment by gregrs-uk** [comment]
@KasperFranz Sorry for the delay with this but I hope to be able to compare our versions soon. Thanks again.

**Comment by gregrs-uk** [comment]
Hopefully fixed now. Just updating data on the development server.
