### ISSUE TITLE
Stopped updating?

### ISSUE THREAD

**Issue by Cj-Malone** [gregrs-uk/fhodot#19]
I think the FHRS data may not be getting updated at the moment.

eg:
I'm being encouraged to replace https://ratings.food.gov.uk/business/en-GB/1629260 with https://ratings.food.gov.uk/business/en-GB/1320052 on https://www.openstreetmap.org/node/5107483874

**Comment by gregrs-uk** [comment]
Yes, I'm afraid it's not being updated at the moment and I haven't got round to fixing this just yet. See https://github.com/gregrs-uk/fhodot/issues/18
