### ISSUE TITLE
Error loading map data

### ISSUE THREAD

**Issue by RedAuburn** [gregrs-uk/fhodot#27]
https://gregrs.dev.openstreetmap.org/fhodot/api/fhrs?l=1b=1&r=0.001&t=1

returns a 500, looks like the api server is broken :(

**Comment by gregrs-uk** [comment]
Thanks @RedAuburn. The development server has just been upgraded so I need to fix the installation.

**Comment by RedAuburn** [comment]
thank you <3 can confirm it's back up and working

**Comment by gregrs-uk** [comment]
Graphs should now be updating properly again
