### ISSUE TITLE
Add support for `not:fhrs:id`

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/fhodot#4]
As requested by @EdLoach for the original FHRS/OSM comparison tool.

See https://github.com/gregrs-uk/python-fhrs-osm/issues/50.

**Comment by gregrs-uk** [comment]
Close in favour of https://github.com/gregrs-uk/fhodot/issues/24 because `old_fhrs:id` is being used more.

**Comment by EdLoach** [comment]
I forgot I'd even suggested not:fhrs:id as I've been using old:fhrs:id more recently - I'll try and get around to switching those to old_fhrs:id at some point which seems to be used more. A note that both variations (old: and old_) have some semi-colon separated lists (and at least old: has a comma separated list, but I don't think that was one of mine).
